/**
 * Email alert system using Resend
 *
 * Sends pricing change alerts to your email
 */

import { PriceChange } from '../src/data/types';

interface EmailPayload {
  to: string;
  subject: string;
  changes: PriceChange[];
  html: string;
}

export function generateEmailHTML(changes: PriceChange[], timestamp: string): string {
  const hasChanges = changes.length > 0;
  const highConfidence = changes.filter(c => c.confidence > 0.9).length;

  // Summary section
  const summary = hasChanges
    ? `<p style="font-size: 16px; color: #1f2937;">
         Found <strong>${changes.length} pricing change${changes.length > 1 ? 's' : ''}</strong>
         across providers (${highConfidence} high-confidence).
       </p>`
    : `<p style="font-size: 16px; color: #1f2937;">
         ✅ No pricing changes detected today. Everything looks stable!
       </p>`;

  // Changes table
  let changesHTML = '';
  if (hasChanges) {
    let tableRows = '';
    for (const change of changes) {
      const color = change.change_percent > 0 ? '#ef4444' : '#10b981';
      const arrow = change.change_percent > 0 ? '↑' : '↓';
      const field = change.field === 'input_per_million' ? 'Input' : 'Output';

      tableRows += `
        <tr>
          <td style="padding: 10px; border: 1px solid #e5e7eb;">${change.provider}</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb;">${change.model}</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb;">${field}</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb; text-align: right;">$${change.old_value.toFixed(2)}</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb; text-align: right; font-weight: bold;">$${change.new_value.toFixed(2)}</td>
          <td style="padding: 10px; border: 1px solid #e5e7eb; text-align: right; color: ${color}; font-weight: bold;">
            ${arrow} ${Math.abs(change.change_percent)}%
          </td>
          <td style="padding: 10px; border: 1px solid #e5e7eb; text-align: right;">${(change.confidence * 100).toFixed(0)}%</td>
        </tr>
      `;
    }

    changesHTML = `
      <table style="border-collapse: collapse; width: 100%; font-family: Arial, sans-serif; margin-top: 15px;">
        <thead>
          <tr style="background: #f3f4f6;">
            <th style="padding: 12px; border: 1px solid #e5e7eb; text-align: left;">Provider</th>
            <th style="padding: 12px; border: 1px solid #e5e7eb; text-align: left;">Model</th>
            <th style="padding: 12px; border: 1px solid #e5e7eb; text-align: left;">Type</th>
            <th style="padding: 12px; border: 1px solid #e5e7eb; text-align: right;">Old</th>
            <th style="padding: 12px; border: 1px solid #e5e7eb; text-align: right;">New</th>
            <th style="padding: 12px; border: 1px solid #e5e7eb; text-align: right;">Change</th>
            <th style="padding: 12px; border: 1px solid #e5e7eb; text-align: right;">Conf.</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
    `;
  }

  // Action buttons
  const actionsHTML = hasChanges
    ? `
      <div style="margin-top: 25px; padding: 20px; background: #f9fafb; border-radius: 8px; border: 1px solid #e5e7eb;">
        <strong style="font-size: 16px;">Next Steps:</strong>
        <div style="margin-top: 15px; display: flex; gap: 10px; flex-wrap: wrap;">
          <a href="https://github.com/yourusername/llm-cost-compass"
             style="padding: 12px 24px; background: #3b82f6; color: white; text-decoration: none; border-radius: 6px; font-weight: bold;">
            Review on GitHub
          </a>
          <a href="http://localhost:3000"
             style="padding: 12px 24px; background: #10b981; color: white; text-decoration: none; border-radius: 6px; font-weight: bold;">
            View Live Site
          </a>
        </div>
        <p style="margin-top: 15px; font-size: 13px; color: #6b7280;">
          Confidence > 90% = auto-publish ready. Lower confidence = manual review needed.
        </p>
      </div>
    `
    : `
      <div style="margin-top: 25px; padding: 20px; background: #f0fdf4; border-radius: 8px; border: 1px solid #bbf7d0;">
        <strong style="font-size: 16px; color: #166534;">✅ All Good!</strong>
        <p style="margin-top: 8px; color: #166534;">
          No pricing changes detected. Your database is up-to-date.
        </p>
      </div>
    `;

  // Footer
  const footer = `
    <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280;">
      <p>Scraped at: ${timestamp}</p>
      <p>Report generated by LLM PriceCheck Daily Update</p>
      <p><a href="#" style="color: #3b82f6;">Unsubscribe</a> | <a href="#" style="color: #3b82f6;">Manage Preferences</a></p>
    </div>
  `;

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: #f3f4f6; }
          .container { max-width: 700px; margin: 0 auto; background: white; padding: 30px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 25px; border-radius: 8px; color: white; margin-bottom: 20px; }
          .header h1 { margin: 0; font-size: 24px; }
          .header p { margin: 5px 0 0 0; opacity: 0.9; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>📊 LLM PriceCheck Daily Report</h1>
            <p>Pricing monitoring for your AI costs</p>
          </div>

          ${summary}
          ${changesHTML}
          ${actionsHTML}
          ${footer}
        </div>
      </body>
    </html>
  `;
}

export async function sendEmailAlert(
  to: string,
  subject: string,
  html: string
): Promise<{ success: boolean; messageId?: string; error?: string }> {
  // Check if Resend API key is available
  const resendApiKey = process.env.RESEND_API_KEY;

  if (!resendApiKey) {
    console.log('⚠️  RESEND_API_KEY not set. Skipping email send.');
    console.log('Email would be sent to:', to);
    console.log('Subject:', subject);
    console.log('\nTo enable emails, add RESEND_API_KEY to your environment variables.');
    return { success: false, error: 'RESEND_API_KEY not configured' };
  }

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'LLM PriceCheck <noreply@llmpricecheck.com>',
        to: [to],
        subject,
        html,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Resend API error: ${error}`);
    }

    const data = await response.json();
    console.log('✅ Email sent successfully:', data.id);
    return { success: true, messageId: data.id };

  } catch (error) {
    console.error('❌ Failed to send email:', error);
    return { success: false, error: String(error) };
  }
}

// Main function for the daily job
export async function sendDailyReport(
  changes: PriceChange[],
  recipient: string
): Promise<void> {
  const timestamp = new Date().toISOString();
  const subject = generateEmailSubject(changes);
  const html = generateEmailHTML(changes, timestamp);

  console.log(`\n📧 Preparing email report...`);
  console.log(`   To: ${recipient}`);
  console.log(`   Subject: ${subject}`);
  console.log(`   Changes detected: ${changes.length}`);

  const result = await sendEmailAlert(recipient, subject, html);

  if (result.success) {
    console.log('✅ Email sent successfully!');
  } else {
    console.log('⚠️  Email not sent (API key not configured)');
  }
}

// If run directly for testing
if (require.main === module) {
  // Test with sample data
  const sampleChanges: PriceChange[] = [
    {
      provider: 'OpenAI',
      model: 'GPT-4o',
      field: 'input_per_million',
      old_value: 5.00,
      new_value: 4.50,
      change_percent: -10.0,
      confidence: 0.95,
      source: 'https://openai.com/pricing',
    },
    {
      provider: 'Google',
      model: 'Gemini Pro',
      field: 'output_per_million',
      old_value: 1.50,
      new_value: 1.25,
      change_percent: -16.7,
      confidence: 0.90,
      source: 'https://cloud.google.com/vertex-ai/pricing',
    },
  ];

  const testEmail = process.argv[2] || 'test@example.com';
  sendDailyReport(sampleChanges, testEmail).then(() => {
    console.log('\nTest complete!');
  });
}
